# Configuration for the Workflow
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_path: data/raw/credit_risk_dataset.csv
  target_path: artifacts/data_ingestion/credit_risk_dataset.csv

data_validation:
  root_dir: artifacts/data_validation
  source_path: artifacts/data_ingestion/credit_risk_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  source_path: artifacts/data_ingestion/credit_risk_dataset.csv
  train_data_path: artifacts/data_preprocessing/train.csv
  test_data_path: artifacts/data_preprocessing/test.csv

model_training:
  root_dir: artifacts/model_training
  model_path: artifacts/model_training/model.joblib
  train_data_path: artifacts/data_preprocessing/train.csv
  test_data_path: artifacts/data_preprocessing/test.csv
  experiment_name: credit-scorecard  # change this if you wanted to create new experiment
  run_name: woe-logreg-scorecard-model  # change this if you wanted to create new run
  mlflow:
    registered_model_name: credit-scoring-model

model_inference:
  root_dir: models/
  model_path: models/model.joblib